#!/usr/bin/env sh
# =========================
# parameter
# =========================
WORKSPACE=${WORKSPACE:-/home/developer/ws}            # 源码根目录
RUNTIME_DIR=${RUNTIME_DIR:-/home/developer/atvruntime}  # 构建产物输出路径
BUILD_TYPE=${BUILD_TYPE:-Release}             # 可选: Debug / Release / RelWithDebInfo
CPU_COUNT=$(nproc)
JOBS=${JOBS:-$((CPU_COUNT - 1))}              # 默认使用 CPU 核心数-1
EVENT_HANDLER=${EVENT_HANDLER:-console_cohesion+}  # 日志显示模式

# =========================
# 构建信息
# =========================
echo "=========================================="
echo "Colcon 构建配置"
echo "Workspace:     $WORKSPACE"
echo "Runtime Dir:   $RUNTIME_DIR"
echo "Build Type:    $BUILD_TYPE"
echo "Parallel Jobs: $JOBS"
echo "Event Handler: $EVENT_HANDLER"
echo "=========================================="
echo

# Build
colcon build \
    --merge-install \
    --event-handlers "${EVENT_HANDLER}" \
    --install-base "${RUNTIME_DIR}/install" \
    --parallel-workers "${JOBS}" \
    --cmake-args \
        -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" \
        -DBUILD_TESTING=OFF

# Build compelete
echo
echo "=========================================="
echo "✅ Build complete!"
echo "👉 install: ${RUNTIME_DIR}/install"
echo "=========================================="
