#!/usr/bin/env bash

set -e

start() {
    if [[ -z "$HOME" ]]; then
        export HOME=/root
    fi

    if is_running; then
        echo 'Error: ATVision daemon is still running!'
        exit 1
    fi

    source /opt/ros/humble/setup.bash

    if [ -z "${ROBOT_TYPE}" ]; then
        echo "Error: Please set robot type first (e.g. 'set-robot sentry')."
        exit 1
    fi

    screen -dmS atvision bash -c "ros2 launch rm_bringup bringup.launch.py robot:=${ROBOT_TYPE}"

    sleep 0.1
    
    if is_running; then
        echo "Successfully started ATVision daemon."
    else
        echo "Error: Failed to start ATVision daemon."
        exit 1
    fi
}

attach() {
    screen -r rmcs
}

stop() {
    if is_running; then
        screen -S rmcs -X quit
        echo "Successfully stopped ATVision daemon."
    fi
}

is_running() {
    if ls '/run/screen/S-root' 2>/dev/null | grep -q '.*\.atvision'; then
        return 0
    else
        return 1
    fi
}

case "$1" in
    start)
        start
        ;;
    attach)
        attach
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo 'Usage: atvision-service {start|attach|stop|restart}'
        exit 1
        ;;
esac

exit 0