#!/usr/bin/env bash
echo "=========================================="
echo " ATVision Start"
echo "=========================================="

rm -rf /tmp/*

service ssh start

atvision-service start

sleep infinity