/armor_detector:
  ros__parameters:
    debug: false
    target_frame: odom
    detect_color: "RED"
    binary_thres: 50

    use_pca: true # 使用PCA算法矫正灯条的角点
    use_ba: true # 使用BA优化算法求解装甲板的Yaw角 

    light.min_ratio: 0.0001
    light.max_ratio: 1.0
    light.max_angle: 35.
    light.color_diff_thresh: 30
    armor.min_light_ratio: 0.8
    armor.min_small_center_distance: 0.8
    armor.max_small_center_distance: 3.5
    armor.min_large_center_distance: 3.5
    armor.max_large_center_distance: 8.0
    armor.max_angle: 40.

    classifier_threshold: 0.5
    ignore_classes: ["negative"]

/armor_detector_ov:
  ros__parameters:
    debug: true
    target_frame: odom
    detect_color: "BLUE"
    model_path: package://armor_detector_ov/model/opt-1208-001.onnx
    model_name: armor_tup
    # model_name: armor_at
    # model_path: package://armor_detector_ov/model/pose_simplified.onnx
    use_gpu: false
    enable_multi_thread: true

/armor_solver:
  ros__parameters:
    debug: true
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    solver:
      bullet_speed: 25.0
      compensator_type: resistance
      controller_delay: 0.0
      gravity: 9.81
      iteration_times: 20
      max_tracking_v_yaw: 60.0
      min_switching_v_yaw: 1.0
      prediction_delay: 0.0
      resistance: 0.092
      shooting_range_height: 0.135
      shooting_range_width: 0.135
      side_angle: 10.0
    target_frame: odom
    tracker:
      lost_threshold: 1.0
      matcher_gate: 5.0
      measure_distance_k: 0.1
      outpost:
        measure_distance_k: 0.2
        sigma_a_yaw: 1.5
        sigma_q_xy: 8.0
        sigma_q_z: 1.7
        yaw_log_k: 0.005
      outpost_matcher_gate: 1.5
      sigma_a_xy: 10.0
      sigma_a_yaw: 10.0
      sigma_a_z: 2.0
      sigma_h: 0.8
      sigma_r: 1.0
      tracking_threshold: 5
      yaw_log_k: 0.005
    use_sim_time: false

/camera_node:
  ros__parameters:
    bayer_cvt_color_quality: 1
    bayer_demosaic_method: ''
    camera_info_url: package://rm_bringup/config/camera_info.yaml
    camera_name: camera
    exposure_time: 3000
    force_8bit_pixel_format: true
    gain: 16.7
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    reconnect_interval_ms: 2000
    reconnect_max_attempts: -1
    timestamp_offset_ms: 0
    use_sensor_data_qos: true
    use_sim_time: false
    # Bayer demosaic method for MV_CC_ConvertPixelType:
    #   nearest | bilinear | optimized (Hamilton)
    bayer_demosaic_method: bilinear


/rm_gimbal:
  ros__parameters:
    debug: true
    planner:
      N: 20
      T: 0.01
      amax: 50.0
      dt_ema_alpha: 0.2
      dt_max: 0.03
      dt_min: 0.002
      q_pitch_pos: 9000000.0
      q_pitch_vel: 0.0
      q_yaw_pos: 9000000.0
      q_yaw_vel: 0.0
      r_pitch_acc: 1.0
      r_yaw_acc: 1.0
    timestamp_offset: 0.006
    target_component_name: armor_detector
    use_planner: true
    use_roll: false
    use_sim_time: false
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
      /tf:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable

/pub_video:
  ros__parameters:
    camera_info_url: package://rm_bringup/config/camera_info.yaml
    camera_name: camera
    image_raw:
      enable_pub_plugins:
      - image_transport/compressed
      - image_transport/raw
      format: jpeg
      jpeg_quality: 95
      png_level: 3
      tiff:
        res_unit: inch
        xdpi: -1
        ydpi: -1
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
      /tf:
        publisher:
          depth: 100
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false
    video_path: /home/developer/ws/assets/armor_demo.mp4
