/armor_detector:
  ros__parameters:
    debug: true
    target_frame: odom
    detect_color: "BLUE"
    binary_thres: 90

    use_nn: false
    device: "CPU"
    openvino.model_path: "0526.onnx"
    use_pca: true # 使用PCA算法矫正灯条的角点
    use_ba: true # 使用BA优化算法求解装甲板的Yaw角 

    light.min_ratio: 0.0001
    light.max_ratio: 1.0
    light.max_angle: 40.0
    light.color_diff_thresh: 20
    armor.min_light_ratio: 0.8
    armor.min_small_center_distance: 0.8
    armor.max_small_center_distance: 3.5
    armor.min_large_center_distance: 3.5
    armor.max_large_center_distance: 8.0
    armor.max_angle: 35.0


    classifier_threshold: 0.5
    ignore_classes: ["negative"]


/armor_solver:
  ros__parameters:
    debug: true
    kalman_filter_type: ukf
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    solver:
      bullet_speed: 22.5
      compensator_type: ideal
      controller_delay: 0.0
      gravity: 9.7997
      iteration_times: 20
      max_tracking_v_yaw: 60.0
      min_switching_v_yaw: 1.0
      prediction_delay: 0.0
      resistance: 0.092
      shooting_range_height: 0.135
      shooting_range_width: 0.135
      side_angle: 0.0
    target_frame: odom
    tracker:
      lost_time_thres: 1.0
      max_match_distance: 0.5
      max_match_yaw_diff: 1.0
      tracking_thres: 2
    ekf:
      sigma2_q_x: 0.05
      sigma2_q_y: 0.05
      sigma2_q_z: 0.05
      sigma2_q_yaw: 1.0
      sigma2_q_r: 80.0

      r_x: 0.0004
      r_y: 0.0004
      r_z: 0.0004
      r_yaw: 0.005


    ukf:
      alpha : 0.3
      beta: 2.
      kappa: 0.

    use_sim_time: false

/camera_node:
  ros__parameters:
    camera_info_url: package://rm_bringup/config/camera_info.yaml
    camera_name: camera
    exposure_time: 5000
    gain: 16.7
    image_raw:
      enable_pub_plugins:
      - image_transport/raw
      format: jpeg
      jpeg_quality: 95
      png_level: 3
      tiff:
        res_unit: inch
        xdpi: -1
        ydpi: -1
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    reconnect_interval_ms: 2000
    reconnect_max_attempts: -1
    use_sensor_data_qos: true
    use_sim_time: false


/rm_gimbal:
  ros__parameters:
    debug: true
    planner:
      N: 20
      T: 0.01
      amax: 50.0
      dt_ema_alpha: 0.2
      dt_max: 0.03
      dt_min: 0.002
      q_pitch_pos: 9000000.0
      q_pitch_vel: 0.0
      q_yaw_pos: 9000000.0
      q_yaw_vel: 0.0
      r_pitch_acc: 1.0
      r_yaw_acc: 1.0
    timestamp_offset: 0.006
    use_planner: true
    use_roll: false
    use_sim_time: false
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
      /tf:
        publisher:
          depth: 100
          durability: volatile
          history: keep_last
          reliability: reliable
