/armor_detector:
  ros__parameters:
    armor:
      max_angle: 35.0
      max_large_center_distance: 5.5
      max_small_center_distance: 3.2
      min_large_center_distance: 3.2
      min_light_ratio: 0.7
      min_small_center_distance: 0.8
    binary_thres: 160
    cam_info_url: package://rm_auto_aim/config/camera_info.yaml
    classifier_threshold: 0.7
    debug: true
    detect_color: 1
    ignore_classes:
    - negative
    light:
      max_angle: 40.0
      max_ratio: 0.4
      min_ratio: 0.1
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    rate: 200
    use_sim_time: false

/armor_tracker:
  ros__parameters:
    debug: true
    ekf:
      r_xyz_factor: 0.0004
      r_yaw: 0.005
      sigma2_q_r: 80.0
      sigma2_q_xyz_max: 0.1
      sigma2_q_xyz_min: 0.05
      sigma2_q_yaw_max: 10.0
      sigma2_q_yaw_min: 5.0
    max_armor_distance: 10.0
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    target_frame: odom
    tracker:
      lost_time_thres: 1.0
      max_match_distance: 0.5
      max_match_yaw_diff: 1.0
      tracking_thres: 5
    use_sim_time: false

/trajectory:
  ros__parameters:
    bullet_velocity: 21.0
    gravity: 9.83
    integration_step: 0.001
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    resistance_coefficient: 0.0
    use_sim_time: false


/camera_node:
  ros__parameters:
    camera_info_url: package://hik_camera/config/camera_info.yaml
    camera_name: narrow_stereo
    exposure_time: 1500
    gain: 16.01140022277832
    image_raw:
      enable_pub_plugins:
      - image_transport/compressedDepth
      - image_transport/compressed
      - image_transport/raw
      - image_transport/theora
      format: jpeg
      jpeg_quality: 95
      png_level: 3
      tiff:
        res_unit: inch
        xdpi: -1
        ydpi: -1
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sensor_data_qos: true
    use_sim_time: false
