/armor_detector:
  ros__parameters:
    debug: true
    armor:
      max_angle: 35.0
      min_light_ratio: 0.8
    detect_color: 1
    binary_thres: 80

    light.min_ratio: 0.1

    classifier_threshold: 0.8
    ignore_classes: ["negative"]

/armor_tracker:
  ros__parameters:
    target_frame: odom
    max_armor_distance: 10.0

    ekf:
      sigma2_q_xyz: 0.05
      sigma2_q_yaw: 5.0
      sigma2_q_r: 80.0

      r_xyz_factor: 0.0004
      r_yaw: 0.005

    tracker:
      max_match_distance: 0.5
      max_match_yaw_diff: 1.0

      tracking_thres: 5
      lost_time_thres: 1.0

/camera_node:
  ros__parameters:
    camera_info_url: package://hik_camera/config/camera_info.yaml
    camera_name: narrow_stereo
    exposure_time: 4000
    gain: 16.01140022277832
    image_raw:
      enable_pub_plugins:
      - image_transport/compressedDepth
      - image_transport/compressed
      - image_transport/raw
      - image_transport/theora
      format: jpeg
      jpeg_quality: 95
      png_level: 3
      tiff:
        res_unit: inch
        xdpi: -1
        ydpi: -1
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sensor_data_qos: true
    use_sim_time: false
