/armor_detector:
  ros__parameters:
    armor:
      max_angle: 35.0
      max_large_center_distance: 5.5
      max_small_center_distance: 3.2
      min_large_center_distance: 3.2
      min_light_ratio: 0.7
      min_small_center_distance: 0.8
    binary_thres: 80
    cam_info_url: package://rm_auto_aim/config/camera_info.yaml
    classifier_threshold: 0.7
    debug: true
    detect_color: 1
    ignore_classes:
    - negative
    light:
      max_angle: 40.0
      max_ratio: 0.4
      min_ratio: 0.1
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    rate: 200
    use_sim_time: false


/armor_tracker:
  ros__parameters:
    target_frame: odom
    max_armor_distance: 10.0

    ekf:
      sigma2_q_xyz: 0.05
      sigma2_q_yaw: 5.0
      sigma2_q_r: 80.0

      r_xyz_factor: 0.0004
      r_yaw: 0.005

    tracker:
      max_match_distance: 0.5
      max_match_yaw_diff: 1.0

      tracking_thres: 5
      lost_time_thres: 1.0

/trajectory:
  ros__parameters:
    bullet_velocity: 21.0
    gravity: 9.83
    integration_step: 0.001
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    resistance_coefficient: 0.0
    use_sim_time: false


/camera_node:
  ros__parameters:
    camera_info_url: package://hik_camera/config/camera_info.yaml
    camera_name: narrow_stereo
    exposure_time: 4000
    gain: 16.01140022277832
    image_raw:
      enable_pub_plugins:
      - image_transport/compressedDepth
      - image_transport/compressed
      - image_transport/raw
      - image_transport/theora
      format: jpeg
      jpeg_quality: 95
      png_level: 3
      tiff:
        res_unit: inch
        xdpi: -1
        ydpi: -1
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sensor_data_qos: true
    use_sim_time: false
