/armor_detector:
  ros__parameters:
    armor:
      max_angle: 35.0
      max_large_center_distance: 5.5
      max_small_center_distance: 3.2
      min_large_center_distance: 3.2
      min_light_ratio: 0.7
      min_small_center_distance: 0.8
    binary_thres: 160
    camera:
      cam_info_url: package://rm_auto_aim/config/camera_info.yaml
      exposure_time: 2
      gain: 16.0
      invert: false
      name: camera
      trigger_mode: false
    classifier_threshold: 0.7
    debug: true
    detect_color: 1
    ignore_classes:
    - negative
    light:
      max_angle: 40.0
      max_ratio: 0.4
      min_ratio: 0.1
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 10
          durability: volatile
          history: keep_last
          reliability: reliable
    rate: 200
    use_sim_time: false

/armor_tracker:
  ros__parameters:
    debug: true
    ekf:
      r_xyz_factor: 0.0004
      r_yaw: 0.005
      sigma2_q_r: 80.0
      sigma2_q_xyz_max: 0.1
      sigma2_q_xyz_min: 0.05
      sigma2_q_yaw_max: 10.0
      sigma2_q_yaw_min: 5.0
    max_armor_distance: 10.0
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 10
          durability: volatile
          history: keep_last
          reliability: reliable
    target_frame: odom
    tracker:
      lost_time_thres: 1.0
      max_match_distance: 0.5
      max_match_yaw_diff: 1.0
      tracking_thres: 5
    use_sim_time: false

/trajectory:
  ros__parameters:
    bullet_velocity: 25.0
    gravity: 9.81
    integration_step: 0.001
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 100
          durability: volatile
          history: keep_last
          reliability: reliable
    resistance_coefficient: 0.0
    target_distance: 8.0
    target_height: 0.0
    use_sim_time: false
